server:
  port: 8010
  # tomcat日志
  tomcat:
    accesslog:
      enabled: true
      directory: ${logger.path}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eurekaServerHost}:8000/eureka

spring:
  application:
    name: springcloud-auth
  # 数据库
  datasource:
    url: ${jdbc.database.url}
    username: ${jdbc.database.username}
    password: ${jdbc.database.password}

mybatis:
    typeAliasesPackage: com.ws.springcloud.auth.server.dao.model
    mapperLocations: classpath:com/ws/springcloud/auth/server/dao/mapper/*.xml
    configLocation: classpath:mybatis-config.xml

logging.level.org.springframework.security: DEBUG