spring:
  application:
    name: springcloud-gateway
  # 容器启动时立即加载servlet
  mvc:
    servlet:
      load-on-startup: 1

# 业务模块路由规则
zuul:
  routes:
    base:
      path: /sc/base/**
      serviceId: springcloud-base
    auth:
      path: /sc/auth/**
      serviceId: springcloud-auth

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000