server:
  port: 8020
  # tomcat日志
  tomcat:
    accesslog:
      enabled: true
      directory: ${logger.path}

spring:
  application:
    name: springcloud-base

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eurekaServerHost}:8000/eureka

logging.level.org.springframework.security: DEBUG
