server:
  port: 8020
  # tomcat日志
  tomcat:
    accesslog:
      enabled: true
      directory: ${logger.path}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eurekaServerHost}:8000/eureka

spring:
  application:
    name: springcloud-base
  # 容器启动时立即加载servlet
  mvc:
    servlet:
      load-on-startup: 1
