server:
  port: 8020
  # tomcat日志
  tomcat:
    accesslog:
      enabled: true
      directory: ${logger.path}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eurekaServerHost}:8000/eureka

spring:
  application:
    name: springcloud-base

security:
  oauth2:
    client:
      clientId: springcloud-service
      clientSecret: springcloud-service
      accessTokenUri: http://localhost:8010/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      id: springcloud-service
      user-info-uri: http://localhost:8010/system/user/current
      prefer-token-info: false

logging.level.org.springframework.security: DEBUG
