server:
  # 指定该Eureka实例的端口
  port: 8000
  # tomcat日志
  tomcat:
    accesslog:
      enabled: true
      directory: ${logger.path}

eureka:
  instance:
    # 指定该Eureka实例的主机名
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    enableSelfPreservation: false